### PR TITLE
Fix URL validation (resolves #128)

### LINKED ISSUE #128: URL validation does not catch improperly formed URLs
**Describe the bug**
Text fields with URL validation does not catch improperly formed URLs.

**To Reproduce**
1. Add a new resource and enter the required info (so you can submit the form in step 3).
2. Add "http://foo" or "http://foo-" as a Publisher Link
3. Submit the resource.
4. Notice that the invalid URL is saved.

**Expected behavior**
Expect an error message to be presented upon submission of the form, and on blur of the URL input field.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
- Version 69.0.1

### PR DESCRIPTION
**Pull request by greatislander**
* [x] I've read the [guidelines for Contributing to the Platform Co-op Toolkit](https://github.com/platform-coop-toolkit/.github/blob/master/CONTRIBUTING.md)
* [x] This isn't a duplicate of an existing pull request

## Description

Fixes URL validation issue identified in #128.

## Steps to test

Repeat steps indicated in #128.

**Expected behavior:** Invalid URL is flagged and user is notified.

## Additional information

Not applicable.

## Related issues

- Resolves #128.

### CODE REVIEW

File: assets/js/admin/admin.js [hunk 1]
```diff
@@ -296,6 +296,33 @@ jQuery( document ).ready( function( $ ) {
...
+				{
+					id: $row.hasClass( 'cmb-repeat' ) ? `${$label.attr( 'for' )}_repeat` : $label.attr( 'for' ),
+					label: $label.text(),
+					type: 'url'
+				}
+			);
+			if ( $row.hasClass( 'cmb-repeat' ) ) {
+				$field.parent( '.cmb-td' ).parent( '.cmb-repeat-row' ).addClass( 'form-invalid' );
+			} else {
+				$row.addClass( 'form-invalid' );
```
Comment (jhung) [inline assets/js/admin/admin.js:318]: Class `form-invalid` gets applied to Permanent Link field if other errors exist and Permanent Link field is valid. See https://github.com/platform-coop-toolkit/learning-commons-framework/issues/155

**Review by jhung — CHANGES_REQUESTED** [review]

File: assets/js/admin/admin.js (hunk 1 above)
Comment (greatislander) [reply assets/js/admin/admin.js:318]: I tried to reproduce this and I couldn't. Did you run `npm run build` to make sure the latest version of the validation script is present after checking out this branch? I'm wondering if that might be the issue.

Comment (jhung) [reply assets/js/admin/admin.js:318]: My apologies. I was running the fix/url-validation branch without having merged changes from the dev branch. Merging dev and running npm run start seems to have resolved this issue I was seeing.

**Review by jhung — APPROVED** [review]
